# Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-first-service
  description: My first Backstage service!
spec:
  type: service
  lifecycle: experimental
  owner: user:shark
---
# User
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: shark
spec:
  profile:
    displayName: Shark
    email: imsharukhisn2@gmail.com
